from pathlib import Path
import sys

import pytest


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.verify_coco_analyst import (
    DEFAULT_VIEW,
    GOVERNED_ORDER_RISK,
    _extract_generated_sql,
)
from scripts.evaluate_coco_analyst import _metric_case, _order_case, _plant_case


def test_coco_analyst_harness_accepts_only_the_governed_semantic_view() -> None:
    result = f"""Generated SQL:
```sql
SELECT * FROM SEMANTIC_VIEW({DEFAULT_VIEW} METRICS order_risk.revenue_at_risk)
-- Generated by Cortex Analyst (request_id: 123)
;
```
"""

    sql = _extract_generated_sql(result, DEFAULT_VIEW)

    assert "SEMANTIC_VIEW" in sql
    assert DEFAULT_VIEW in sql


@pytest.mark.parametrize(
    "sql",
    [
        "DELETE FROM SUPPLYCHAIN_TRUST_GRAPH.AUDIT.AUDIT_EVENTS",
        "SELECT * FROM OTHER_DB.PUBLIC.OTHER_VIEW",
        f"SELECT * FROM SEMANTIC_VIEW({DEFAULT_VIEW}); SELECT CURRENT_USER()",
    ],
)
def test_coco_analyst_harness_rejects_unsafe_or_unexpected_sql(sql: str) -> None:
    result = f"```sql\n{sql}\n```"

    with pytest.raises(ValueError):
        _extract_generated_sql(result, DEFAULT_VIEW)


def test_coco_evaluation_case_contracts() -> None:
    assert _metric_case([
        {"revenue_at_risk": 586_000, "orders_at_risk": 3, "supplier_id": "SUP-042"}
    ])
    assert _order_case([
        {"order_id": "SO-7103", "customer_name": "Helios Industrial", "customer_tier": "Strategic"},
        {"order_id": "SO-7101", "customer_name": "Apex Mobility", "customer_tier": "Strategic"},
        {"order_id": "SO-7102", "customer_name": "Meridian Robotics", "customer_tier": "Priority"},
    ])
    assert _plant_case([
        {"plant_id": "PLT-BLR", "plant_name": "Bengaluru Systems", "revenue_at_risk": 196_000, "orders_at_risk": 1},
        {"plant_id": "PLT-PUN", "plant_name": "Pune Assembly", "revenue_at_risk": 390_000, "orders_at_risk": 2},
    ])


def test_coco_eval_allows_only_declared_governed_logical_table() -> None:
    result = f"""```sql
WITH risk AS (
  SELECT * FROM {GOVERNED_ORDER_RISK}
)
SELECT supplier_id FROM risk
```
"""

    assert _extract_generated_sql(
        result,
        DEFAULT_VIEW,
        allowed_relations=(GOVERNED_ORDER_RISK,),
    )

    with pytest.raises(ValueError):
        _extract_generated_sql(
            result.replace(GOVERNED_ORDER_RISK, "SUPPLYCHAIN_TRUST_GRAPH.CORE.SUPPLIERS"),
            DEFAULT_VIEW,
            allowed_relations=(GOVERNED_ORDER_RISK,),
        )
