USE ROLE ACCOUNTADMIN;
USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;

CREATE ROLE IF NOT EXISTS SUPPLYCHAIN_APP_SERVICE_OWNER
  COMMENT = 'Owns Snowpark Container Services infrastructure; inherits data-plane runtime access';
GRANT ROLE SUPPLYCHAIN_APP_RUNTIME TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;
GRANT ROLE SUPPLYCHAIN_APP_SERVICE_OWNER TO ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS APP WITH MANAGED ACCESS
  COMMENT = 'Snowflake-hosted application services and OCI images';

CREATE IMAGE REPOSITORY IF NOT EXISTS APP.SUPPLYCHAIN_IMAGES
  COMMENT = 'Linux AMD64 application images for SupplyChain Trust Graph';

CREATE COMPUTE POOL IF NOT EXISTS SUPPLYCHAIN_APP_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  AUTO_SUSPEND_SECS = 300
  COMMENT = 'Smallest available pool for the governed supply-chain web service';

ALTER COMPUTE POOL SUPPLYCHAIN_APP_POOL SET
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300;

GRANT USAGE ON DATABASE SUPPLYCHAIN_TRUST_GRAPH TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;
GRANT USAGE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.APP TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;
GRANT CREATE SERVICE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.APP TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;
GRANT READ ON IMAGE REPOSITORY SUPPLYCHAIN_TRUST_GRAPH.APP.SUPPLYCHAIN_IMAGES
  TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;
GRANT USAGE, MONITOR ON COMPUTE POOL SUPPLYCHAIN_APP_POOL
  TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SUPPLYCHAIN_APP_SERVICE_OWNER;

REVOKE CREATE SERVICE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.APP FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE READ ON IMAGE REPOSITORY SUPPLYCHAIN_TRUST_GRAPH.APP.SUPPLYCHAIN_IMAGES
  FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE USAGE, MONITOR ON COMPUTE POOL SUPPLYCHAIN_APP_POOL
  FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE BIND SERVICE ENDPOINT ON ACCOUNT FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE USAGE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.APP FROM ROLE SUPPLYCHAIN_APP_RUNTIME;

GRANT USAGE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.APP TO ROLE SUPPLYCHAIN_APP_READONLY;
