-- SupplyChain Trust Graph · Snowflake schema
-- Run with a role that can create a database, schema, tables, views, and semantic views.

CREATE DATABASE IF NOT EXISTS SUPPLYCHAIN_TRUST_GRAPH;
CREATE SCHEMA IF NOT EXISTS SUPPLYCHAIN_TRUST_GRAPH.CORE;
USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS SUPPLIERS (
  SUPPLIER_ID VARCHAR NOT NULL PRIMARY KEY,
  SUPPLIER_NAME VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL,
  RISK_TIER VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'SUPPLIER_MASTER',
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PARTS (
  PART_ID VARCHAR NOT NULL PRIMARY KEY,
  PART_NAME VARCHAR NOT NULL,
  CATEGORY VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'ERP',
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PLANTS (
  PLANT_ID VARCHAR NOT NULL PRIMARY KEY,
  PLANT_NAME VARCHAR NOT NULL,
  CITY VARCHAR NOT NULL,
  COUNTRY VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'ERP',
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SUPPLIER_PARTS (
  SUPPLIER_ID VARCHAR NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID),
  PART_ID VARCHAR NOT NULL REFERENCES PARTS(PART_ID),
  PLANT_ID VARCHAR NOT NULL REFERENCES PLANTS(PLANT_ID),
  APPROVED BOOLEAN NOT NULL,
  LEAD_TIME_DAYS NUMBER(5,0) NOT NULL,
  AVAILABLE_CAPACITY NUMBER(12,0) NOT NULL,
  COST_BAND VARCHAR NOT NULL,
  QUALIFIED_AT TIMESTAMP_TZ,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'SUPPLIER_MASTER',
  PRIMARY KEY (SUPPLIER_ID, PART_ID, PLANT_ID)
);

CREATE TABLE IF NOT EXISTS INVENTORY (
  PART_ID VARCHAR NOT NULL REFERENCES PARTS(PART_ID),
  PLANT_ID VARCHAR NOT NULL REFERENCES PLANTS(PLANT_ID),
  ON_HAND NUMBER(12,0) NOT NULL,
  SAFETY_STOCK NUMBER(12,0) NOT NULL,
  DAILY_DEMAND NUMBER(12,2) NOT NULL,
  SNAPSHOT_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'WMS',
  PRIMARY KEY (PART_ID, PLANT_ID, SNAPSHOT_AT)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID VARCHAR NOT NULL PRIMARY KEY,
  CUSTOMER_NAME VARCHAR NOT NULL,
  CUSTOMER_TIER VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'CRM',
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SALES_ORDERS (
  ORDER_ID VARCHAR NOT NULL PRIMARY KEY,
  CUSTOMER_ID VARCHAR NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  PART_ID VARCHAR NOT NULL REFERENCES PARTS(PART_ID),
  PLANT_ID VARCHAR NOT NULL REFERENCES PLANTS(PLANT_ID),
  REQUIRED_DATE DATE NOT NULL,
  ORDER_VALUE NUMBER(18,2) NOT NULL,
  QUANTITY NUMBER(12,0) NOT NULL,
  STATUS VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'ERP',
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SHIPMENTS (
  SHIPMENT_ID VARCHAR NOT NULL PRIMARY KEY,
  SUPPLIER_ID VARCHAR NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID),
  PART_ID VARCHAR NOT NULL REFERENCES PARTS(PART_ID),
  PLANT_ID VARCHAR NOT NULL REFERENCES PLANTS(PLANT_ID),
  ORDER_ID VARCHAR REFERENCES SALES_ORDERS(ORDER_ID),
  QUANTITY NUMBER(12,0) NOT NULL,
  PROMISED_DATE DATE NOT NULL,
  RECEIVED_DATE DATE,
  STATUS VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'TMS',
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SUPPLIER_DOCUMENTS (
  DOCUMENT_ID VARCHAR NOT NULL PRIMARY KEY,
  SUPPLIER_ID VARCHAR NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID),
  PART_ID VARCHAR REFERENCES PARTS(PART_ID),
  DOCUMENT_TYPE VARCHAR NOT NULL,
  TITLE VARCHAR NOT NULL,
  DETAIL VARCHAR NOT NULL,
  OBSERVED_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS DISRUPTION_EVENTS (
  DISRUPTION_ID VARCHAR NOT NULL PRIMARY KEY,
  SUPPLIER_ID VARCHAR NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID),
  DELAY_DAYS NUMBER(5,0) NOT NULL,
  REPORTED_AT TIMESTAMP_TZ NOT NULL,
  STATUS VARCHAR NOT NULL,
  SOURCE_DOCUMENT_ID VARCHAR REFERENCES SUPPLIER_DOCUMENTS(DOCUMENT_ID),
  CORRELATION_ID VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL DEFAULT 'SUPPLIER_PORTAL'
);

CREATE TABLE IF NOT EXISTS MITIGATION_ACTIONS (
  AUDIT_ID VARCHAR NOT NULL,
  ACTION_ID VARCHAR NOT NULL PRIMARY KEY,
  DISRUPTION_ID VARCHAR NOT NULL REFERENCES DISRUPTION_EVENTS(DISRUPTION_ID),
  PART_ID VARCHAR NOT NULL REFERENCES PARTS(PART_ID),
  PLANT_ID VARCHAR NOT NULL REFERENCES PLANTS(PLANT_ID),
  PROPOSED_SUPPLIER_ID VARCHAR NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID),
  ACTION_TYPE VARCHAR NOT NULL,
  OWNER VARCHAR NOT NULL,
  OWNER_ID VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  RATIONALE VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  ACTION_VERSION NUMBER(10,0) NOT NULL DEFAULT 1,
  POLICY_DECISION_ID VARCHAR NOT NULL,
  QUALIFICATION_CHECKED_AT TIMESTAMP_TZ NOT NULL,
  APPROVED_BY VARCHAR,
  APPROVED_BY_ID VARCHAR,
  APPROVED_AT TIMESTAMP_TZ,
  APPROVAL_REASON VARCHAR,
  RETURNED_BY VARCHAR,
  RETURNED_BY_ID VARCHAR,
  RETURNED_AT TIMESTAMP_TZ,
  REVISION_REASON VARCHAR,
  CORRELATION_ID VARCHAR NOT NULL,
  CONSTRAINT MITIGATION_REQUIRES_HUMAN_APPROVAL CHECK (
    STATUS IN ('PENDING_APPROVAL', 'APPROVED', 'RETURNED_FOR_REVISION', 'REJECTED')
  )
);

CREATE TABLE IF NOT EXISTS AUDIT_EVENTS (
  AUDIT_ID VARCHAR NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR NOT NULL,
  ACTOR VARCHAR NOT NULL,
  SUMMARY VARCHAR NOT NULL,
  ENTITY_TYPE VARCHAR NOT NULL,
  ENTITY_ID VARCHAR NOT NULL,
  CORRELATION_ID VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS DECISION_IDEMPOTENCY (
  CACHE_KEY VARCHAR NOT NULL PRIMARY KEY,
  ACTION_ID VARCHAR NOT NULL REFERENCES MITIGATION_ACTIONS(ACTION_ID),
  RESULT VARIANT NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- Governance contract: application roles append audit rows but never update or delete them.
CREATE ROLE IF NOT EXISTS SUPPLYCHAIN_APP_READONLY;
GRANT USAGE ON DATABASE SUPPLYCHAIN_TRUST_GRAPH TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT USAGE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT ROLE SUPPLYCHAIN_APP_READONLY TO ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SUPPLYCHAIN_APP_RUNTIME;
GRANT USAGE ON DATABASE SUPPLYCHAIN_TRUST_GRAPH TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT USAGE ON SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLYCHAIN_TRUST_GRAPH.CORE TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT INSERT, UPDATE ON TABLE MITIGATION_ACTIONS TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT INSERT ON TABLE AUDIT_EVENTS TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT INSERT, SELECT ON TABLE DECISION_IDEMPOTENCY TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT ROLE SUPPLYCHAIN_APP_RUNTIME TO ROLE ACCOUNTADMIN;
