USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;
USE SCHEMA CORE;

-- Governed analytical grain: one open order joined only through declared ontology keys.
CREATE OR REPLACE VIEW GOVERNED_ORDER_RISK AS
WITH ACTIVE_DELAY AS (
  SELECT SUPPLIER_ID, DELAY_DAYS
  FROM DISRUPTION_EVENTS
  WHERE STATUS = 'ACTIVE'
),
PROJECTED_INBOUND_RAW AS (
  SELECT
    S.SUPPLIER_ID,
    S.PART_ID,
    S.PLANT_ID,
    S.SHIPMENT_ID,
    S.QUANTITY AS INBOUND_QUANTITY,
    S.PROMISED_DATE AS ORIGINAL_ETA,
    DATEADD('day', COALESCE(D.DELAY_DAYS, 0), S.PROMISED_DATE) AS PROJECTED_ETA
  FROM SHIPMENTS S
  JOIN ACTIVE_DELAY D ON D.SUPPLIER_ID = S.SUPPLIER_ID
  WHERE S.STATUS = 'IN_TRANSIT'
),
PROJECTED_INBOUND AS (
  SELECT
    SUPPLIER_ID,
    PART_ID,
    PLANT_ID,
    LISTAGG(SHIPMENT_ID, ',') WITHIN GROUP (ORDER BY SHIPMENT_ID) AS SHIPMENT_IDS,
    SUM(INBOUND_QUANTITY) AS INBOUND_QUANTITY,
    MIN(ORIGINAL_ETA) AS ORIGINAL_ETA,
    MIN(PROJECTED_ETA) AS PROJECTED_ETA
  FROM PROJECTED_INBOUND_RAW
  GROUP BY SUPPLIER_ID, PART_ID, PLANT_ID
),
LATEST_INVENTORY AS (
  SELECT *
  FROM INVENTORY
  QUALIFY ROW_NUMBER() OVER (PARTITION BY PART_ID, PLANT_ID ORDER BY SNAPSHOT_AT DESC) = 1
),
ORDER_CONTEXT AS (
  SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_TIER,
    O.PART_ID,
    P.PART_NAME,
    O.PLANT_ID,
    PL.PLANT_NAME,
    I.SUPPLIER_ID,
    I.SHIPMENT_IDS,
    O.REQUIRED_DATE,
    I.ORIGINAL_ETA,
    I.PROJECTED_ETA,
    O.ORDER_VALUE,
    O.QUANTITY AS ORDER_QUANTITY,
    GREATEST(L.ON_HAND - L.SAFETY_STOCK, 0) AS ALLOCATABLE_INVENTORY,
    I.INBOUND_QUANTITY,
    O.SOURCE_SYSTEM AS ORDER_SOURCE_SYSTEM,
    L.SNAPSHOT_AT AS INVENTORY_SOURCE_TIMESTAMP
  FROM SALES_ORDERS O
  JOIN CUSTOMERS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
  JOIN PARTS P ON P.PART_ID = O.PART_ID
  JOIN PLANTS PL ON PL.PLANT_ID = O.PLANT_ID
  JOIN PROJECTED_INBOUND I ON I.PART_ID = O.PART_ID AND I.PLANT_ID = O.PLANT_ID
  JOIN LATEST_INVENTORY L ON L.PART_ID = O.PART_ID AND L.PLANT_ID = O.PLANT_ID
  WHERE O.STATUS = 'OPEN'
),
ALLOCATED_ORDER_CONTEXT AS (
  SELECT
    *,
    SUM(ORDER_QUANTITY) OVER (
      PARTITION BY SUPPLIER_ID, PART_ID, PLANT_ID
      ORDER BY REQUIRED_DATE, ORDER_ID
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUMULATIVE_ORDER_DEMAND
  FROM ORDER_CONTEXT
)
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CUSTOMER_TIER,
  PART_ID,
  PART_NAME,
  PLANT_ID,
  PLANT_NAME,
  SUPPLIER_ID,
  SHIPMENT_IDS,
  REQUIRED_DATE,
  ORIGINAL_ETA,
  PROJECTED_ETA,
  ORDER_VALUE,
  ORDER_QUANTITY,
  ALLOCATABLE_INVENTORY,
  CUMULATIVE_ORDER_DEMAND,
  INBOUND_QUANTITY,
  ALLOCATABLE_INVENTORY
    + IFF(PROJECTED_ETA <= REQUIRED_DATE, INBOUND_QUANTITY, 0)
    < CUMULATIVE_ORDER_DEMAND AS IS_AT_RISK,
  IFF(
    ALLOCATABLE_INVENTORY
      + IFF(PROJECTED_ETA <= REQUIRED_DATE, INBOUND_QUANTITY, 0)
      < CUMULATIVE_ORDER_DEMAND,
    ORDER_VALUE,
    0
  ) AS AT_RISK_VALUE,
  ORDER_SOURCE_SYSTEM,
  INVENTORY_SOURCE_TIMESTAMP
FROM ALLOCATED_ORDER_CONTEXT;

CREATE OR REPLACE VIEW GOVERNED_DELIVERY_PERFORMANCE AS
SELECT
  SUPPLIER_ID,
  COUNT_IF(RECEIVED_DATE <= PROMISED_DATE) AS DELIVERIES_ON_TIME,
  COUNT(*) AS DELIVERIES_DUE,
  DIV0(COUNT_IF(RECEIVED_DATE <= PROMISED_DATE), COUNT(*)) AS ON_TIME_DELIVERY_RATE
FROM SHIPMENTS
WHERE STATUS = 'RECEIVED'
GROUP BY SUPPLIER_ID;

CREATE OR REPLACE VIEW GOVERNED_PLANT_STOCKOUT_RISK AS
WITH LATEST_INVENTORY AS (
  SELECT * FROM INVENTORY
  QUALIFY ROW_NUMBER() OVER (PARTITION BY PART_ID, PLANT_ID ORDER BY SNAPSHOT_AT DESC) = 1
)
SELECT
  SP.SUPPLIER_ID,
  I.PART_ID,
  I.PLANT_ID,
  I.ON_HAND,
  I.SAFETY_STOCK,
  SP.LEAD_TIME_DAYS,
  DATEADD('day', SP.LEAD_TIME_DAYS, TO_DATE(I.SNAPSHOT_AT)) AS LEAD_TIME_WINDOW_END,
  COALESCE(SUM(IFF(
    S.STATUS = 'IN_TRANSIT'
      AND DATEADD('day', COALESCE(D.DELAY_DAYS, 0), S.PROMISED_DATE)
        <= DATEADD('day', SP.LEAD_TIME_DAYS, TO_DATE(I.SNAPSHOT_AT)),
    S.QUANTITY,
    0
  )), 0) AS CONFIRMED_INBOUND_INSIDE_WINDOW,
  I.DAILY_DEMAND * SP.LEAD_TIME_DAYS AS LEAD_TIME_DEMAND,
  I.ON_HAND + COALESCE(SUM(IFF(
    S.STATUS = 'IN_TRANSIT'
      AND DATEADD('day', COALESCE(D.DELAY_DAYS, 0), S.PROMISED_DATE)
        <= DATEADD('day', SP.LEAD_TIME_DAYS, TO_DATE(I.SNAPSHOT_AT)),
    S.QUANTITY,
    0
  )), 0) < I.DAILY_DEMAND * SP.LEAD_TIME_DAYS AS IS_STOCKOUT_RISK,
  I.SNAPSHOT_AT AS SOURCE_TIMESTAMP
FROM LATEST_INVENTORY I
JOIN SUPPLIER_PARTS SP
  ON SP.PART_ID = I.PART_ID AND SP.PLANT_ID = I.PLANT_ID AND SP.APPROVED = TRUE
JOIN DISRUPTION_EVENTS ACTIVE_D
  ON ACTIVE_D.SUPPLIER_ID = SP.SUPPLIER_ID AND ACTIVE_D.STATUS = 'ACTIVE'
LEFT JOIN SHIPMENTS S
  ON S.PART_ID = I.PART_ID AND S.PLANT_ID = I.PLANT_ID AND S.SUPPLIER_ID = SP.SUPPLIER_ID
LEFT JOIN DISRUPTION_EVENTS D
  ON D.SUPPLIER_ID = S.SUPPLIER_ID AND D.STATUS = 'ACTIVE'
GROUP BY
  SP.SUPPLIER_ID, I.PART_ID, I.PLANT_ID, I.ON_HAND, I.SAFETY_STOCK, I.DAILY_DEMAND,
  I.SNAPSHOT_AT, SP.LEAD_TIME_DAYS;

-- Native Snowflake Semantic View. Clause order follows Snowflake DDL requirements:
-- TABLES → FACTS → DIMENSIONS → METRICS.
CREATE OR REPLACE SEMANTIC VIEW SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TABLES (
    order_risk AS SUPPLYCHAIN_TRUST_GRAPH.CORE.GOVERNED_ORDER_RISK
      PRIMARY KEY (ORDER_ID)
      WITH SYNONYMS = ('affected orders', 'customer orders')
      COMMENT = 'Governed open-order impact grain'
  )
  FACTS (
    order_risk.order_value AS order_risk.ORDER_VALUE
      COMMENT = 'Committed open-order value in USD',
    order_risk.at_risk_value AS order_risk.AT_RISK_VALUE
      COMMENT = 'Order value included only when the governed at-risk test passes'
  )
  DIMENSIONS (
    order_risk.order_id AS order_risk.ORDER_ID,
    order_risk.customer_name AS order_risk.CUSTOMER_NAME,
    order_risk.customer_tier AS order_risk.CUSTOMER_TIER,
    order_risk.part_id AS order_risk.PART_ID,
    order_risk.part_name AS order_risk.PART_NAME,
    order_risk.plant_id AS order_risk.PLANT_ID,
    order_risk.plant_name AS order_risk.PLANT_NAME,
    order_risk.supplier_id AS order_risk.SUPPLIER_ID,
    order_risk.required_date AS order_risk.REQUIRED_DATE,
    order_risk.projected_eta AS order_risk.PROJECTED_ETA,
    order_risk.is_at_risk AS order_risk.IS_AT_RISK
      WITH SYNONYMS = ('late supply', 'order exposed')
  )
  METRICS (
    order_risk.revenue_at_risk AS SUM(order_risk.AT_RISK_VALUE)
      WITH SYNONYMS = ('exposed revenue', 'revenue exposure')
      COMMENT = 'Sum of open-order value where protected stock plus inbound arriving by the required date cannot satisfy cumulative demand',
    order_risk.orders_at_risk AS COUNT_IF(order_risk.IS_AT_RISK)
      COMMENT = 'Count of open orders passing the governed at-risk test'
  )
  COMMENT = 'Governed supply-chain impact model for consistent conversational analytics'
  AI_SQL_GENERATION 'Use only declared metrics. Never substitute total order value for revenue_at_risk. Protect safety stock.'
  AI_VERIFIED_QUERIES (
    sup_042_revenue_at_risk AS (
      QUESTION 'What revenue is at risk from the SUP-042 delay?'
      VERIFIED_AT 1790658000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(purpose = governed_product_validation)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC METRICS order_risk.revenue_at_risk DIMENSIONS order_risk.supplier_id WHERE order_risk.supplier_id = ''SUP-042'')'
    )
  );

-- Expected demo result: $586,000 across SO-7101, SO-7102, and SO-7103.
SELECT * FROM SEMANTIC_VIEW(
  SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  METRICS order_risk.revenue_at_risk, order_risk.orders_at_risk
  DIMENSIONS order_risk.supplier_id
  WHERE order_risk.supplier_id = 'SUP-042'
);
