USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;
USE SCHEMA CORE;

-- Deployment proof: this query must return PASS before a submission demo.
WITH ACTUAL AS (
  SELECT
    SUM(AT_RISK_VALUE) AS REVENUE_AT_RISK,
    COUNT_IF(IS_AT_RISK) AS ORDERS_AT_RISK
  FROM GOVERNED_ORDER_RISK
  WHERE SUPPLIER_ID = 'SUP-042'
),
EXPECTED AS (
  SELECT 586000::NUMBER(18,2) AS REVENUE_AT_RISK, 3::NUMBER AS ORDERS_AT_RISK
)
SELECT
  IFF(
    A.REVENUE_AT_RISK = E.REVENUE_AT_RISK
      AND A.ORDERS_AT_RISK = E.ORDERS_AT_RISK,
    'PASS',
    'FAIL'
  ) AS VALIDATION_STATUS,
  A.REVENUE_AT_RISK AS ACTUAL_REVENUE_AT_RISK,
  E.REVENUE_AT_RISK AS EXPECTED_REVENUE_AT_RISK,
  A.ORDERS_AT_RISK AS ACTUAL_ORDERS_AT_RISK,
  E.ORDERS_AT_RISK AS EXPECTED_ORDERS_AT_RISK,
  CURRENT_TIMESTAMP() AS VALIDATED_AT
FROM ACTUAL A
CROSS JOIN EXPECTED E;

-- Negative control: the unapproved supplier must never enter the eligible set.
SELECT
  IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS UNAPPROVED_SUPPLIER_GATE,
  COUNT(*) AS LEAKED_ROWS
FROM SUPPLIER_PARTS
WHERE SUPPLIER_ID = 'SUP-031'
  AND PART_ID = 'PRT-AX14'
  AND PLANT_ID = 'PLT-PUN'
  AND APPROVED = TRUE;

-- Native semantic-view proof used in the demo recording.
SELECT * FROM SEMANTIC_VIEW(
  SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  METRICS order_risk.revenue_at_risk, order_risk.orders_at_risk
  DIMENSIONS order_risk.supplier_id
  WHERE order_risk.supplier_id = 'SUP-042'
);
