-- SupplyChain Trust Graph · layered security zones
-- Additive migration: CORE remains a private compatibility/landing schema while
-- application roles move to purpose-specific governed, workflow, and audit zones.

USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;

CREATE SCHEMA IF NOT EXISTS SOURCE WITH MANAGED ACCESS
  COMMENT = 'Private normalized source boundary over legacy CORE landing objects';
CREATE SCHEMA IF NOT EXISTS GOVERNED WITH MANAGED ACCESS
  COMMENT = 'Read-only governed entities, analytical views, and semantic views';
CREATE SCHEMA IF NOT EXISTS WORKFLOW WITH MANAGED ACCESS
  COMMENT = 'Mutable mitigation workflow state; no ERP or purchase-order execution';
CREATE SCHEMA IF NOT EXISTS AUDIT WITH MANAGED ACCESS
  COMMENT = 'Append-only attributable audit evidence';

-- SOURCE is intentionally not granted to either application role. Secure views
-- isolate the legacy landing schema without duplicating governed source records.
CREATE OR REPLACE SECURE VIEW SOURCE.SUPPLIERS AS SELECT * FROM CORE.SUPPLIERS;
CREATE OR REPLACE SECURE VIEW SOURCE.PARTS AS SELECT * FROM CORE.PARTS;
CREATE OR REPLACE SECURE VIEW SOURCE.PLANTS AS SELECT * FROM CORE.PLANTS;
CREATE OR REPLACE SECURE VIEW SOURCE.SUPPLIER_PARTS AS SELECT * FROM CORE.SUPPLIER_PARTS;
CREATE OR REPLACE SECURE VIEW SOURCE.INVENTORY AS SELECT * FROM CORE.INVENTORY;
CREATE OR REPLACE SECURE VIEW SOURCE.CUSTOMERS AS SELECT * FROM CORE.CUSTOMERS;
CREATE OR REPLACE SECURE VIEW SOURCE.SALES_ORDERS AS SELECT * FROM CORE.SALES_ORDERS;
CREATE OR REPLACE SECURE VIEW SOURCE.SHIPMENTS AS SELECT * FROM CORE.SHIPMENTS;
CREATE OR REPLACE SECURE VIEW SOURCE.SUPPLIER_DOCUMENTS AS SELECT * FROM CORE.SUPPLIER_DOCUMENTS;
CREATE OR REPLACE SECURE VIEW SOURCE.DISRUPTION_EVENTS AS SELECT * FROM CORE.DISRUPTION_EVENTS;

-- The runtime reads only these governed contracts. It receives no direct CORE
-- or SOURCE access, so later masking/row-access policies can be applied here.
CREATE OR REPLACE SECURE VIEW GOVERNED.SUPPLIERS AS SELECT * FROM SOURCE.SUPPLIERS;
CREATE OR REPLACE SECURE VIEW GOVERNED.PARTS AS SELECT * FROM SOURCE.PARTS;
CREATE OR REPLACE SECURE VIEW GOVERNED.PLANTS AS SELECT * FROM SOURCE.PLANTS;
CREATE OR REPLACE SECURE VIEW GOVERNED.SUPPLIER_PARTS AS SELECT * FROM SOURCE.SUPPLIER_PARTS;
CREATE OR REPLACE SECURE VIEW GOVERNED.INVENTORY AS SELECT * FROM SOURCE.INVENTORY;
CREATE OR REPLACE SECURE VIEW GOVERNED.CUSTOMERS AS SELECT * FROM SOURCE.CUSTOMERS;
CREATE OR REPLACE SECURE VIEW GOVERNED.SALES_ORDERS AS SELECT * FROM SOURCE.SALES_ORDERS;
CREATE OR REPLACE SECURE VIEW GOVERNED.SHIPMENTS AS SELECT * FROM SOURCE.SHIPMENTS;
CREATE OR REPLACE SECURE VIEW GOVERNED.SUPPLIER_DOCUMENTS AS SELECT * FROM SOURCE.SUPPLIER_DOCUMENTS;
CREATE OR REPLACE SECURE VIEW GOVERNED.DISRUPTION_EVENTS AS SELECT * FROM SOURCE.DISRUPTION_EVENTS;
CREATE OR REPLACE SECURE VIEW GOVERNED.ORDER_RISK AS SELECT * FROM CORE.GOVERNED_ORDER_RISK;
CREATE OR REPLACE SECURE VIEW GOVERNED.DELIVERY_PERFORMANCE AS
  SELECT * FROM CORE.GOVERNED_DELIVERY_PERFORMANCE;
CREATE OR REPLACE SECURE VIEW GOVERNED.PLANT_STOCKOUT_RISK AS
  SELECT * FROM CORE.GOVERNED_PLANT_STOCKOUT_RISK;

-- Mutable workflow and append-only audit state are physically separated from
-- analytical entities. Existing governed demo rows are copied without removal.
CREATE TABLE IF NOT EXISTS WORKFLOW.MITIGATION_ACTIONS LIKE CORE.MITIGATION_ACTIONS;
INSERT INTO WORKFLOW.MITIGATION_ACTIONS
SELECT C.*
FROM CORE.MITIGATION_ACTIONS C
WHERE NOT EXISTS (
  SELECT 1 FROM WORKFLOW.MITIGATION_ACTIONS W WHERE W.ACTION_ID = C.ACTION_ID
);

CREATE TABLE IF NOT EXISTS WORKFLOW.DECISION_IDEMPOTENCY LIKE CORE.DECISION_IDEMPOTENCY;
INSERT INTO WORKFLOW.DECISION_IDEMPOTENCY
SELECT C.*
FROM CORE.DECISION_IDEMPOTENCY C
WHERE NOT EXISTS (
  SELECT 1 FROM WORKFLOW.DECISION_IDEMPOTENCY W WHERE W.CACHE_KEY = C.CACHE_KEY
);

CREATE TABLE IF NOT EXISTS AUDIT.AUDIT_EVENTS LIKE CORE.AUDIT_EVENTS;
INSERT INTO AUDIT.AUDIT_EVENTS
SELECT C.*
FROM CORE.AUDIT_EVENTS C
WHERE NOT EXISTS (
  SELECT 1 FROM AUDIT.AUDIT_EVENTS A WHERE A.AUDIT_ID = C.AUDIT_ID
);

CREATE OR REPLACE SEMANTIC VIEW GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TABLES (
    order_risk AS SUPPLYCHAIN_TRUST_GRAPH.GOVERNED.ORDER_RISK
      PRIMARY KEY (ORDER_ID)
      WITH SYNONYMS = ('affected orders', 'customer orders')
      COMMENT = 'Governed open-order impact grain'
  )
  FACTS (
    order_risk.order_value AS order_risk.ORDER_VALUE
      COMMENT = 'Committed open-order value in USD',
    order_risk.at_risk_value AS order_risk.AT_RISK_VALUE
      COMMENT = 'Order value included only when the governed at-risk test passes'
  )
  DIMENSIONS (
    order_risk.order_id AS order_risk.ORDER_ID,
    order_risk.customer_name AS order_risk.CUSTOMER_NAME,
    order_risk.customer_tier AS order_risk.CUSTOMER_TIER,
    order_risk.part_id AS order_risk.PART_ID,
    order_risk.part_name AS order_risk.PART_NAME,
    order_risk.plant_id AS order_risk.PLANT_ID,
    order_risk.plant_name AS order_risk.PLANT_NAME,
    order_risk.supplier_id AS order_risk.SUPPLIER_ID,
    order_risk.required_date AS order_risk.REQUIRED_DATE,
    order_risk.projected_eta AS order_risk.PROJECTED_ETA,
    order_risk.is_at_risk AS order_risk.IS_AT_RISK
      WITH SYNONYMS = ('late supply', 'order exposed')
  )
  METRICS (
    order_risk.revenue_at_risk AS SUM(order_risk.AT_RISK_VALUE)
      WITH SYNONYMS = ('exposed revenue', 'revenue exposure')
      COMMENT = 'Sum of open-order value where protected stock plus inbound arriving by the required date cannot satisfy cumulative demand',
    order_risk.orders_at_risk AS COUNT_IF(order_risk.IS_AT_RISK)
      COMMENT = 'Count of open orders passing the governed at-risk test'
  )
  COMMENT = 'Governed supply-chain impact model isolated in the analytics security zone'
  AI_SQL_GENERATION 'Use only declared metrics. Never substitute total order value for revenue_at_risk. Protect safety stock.'
  AI_VERIFIED_QUERIES (
    sup_042_revenue_at_risk AS (
      QUESTION 'What revenue is at risk from the SUP-042 delay?'
      VERIFIED_AT 1790658000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(purpose = governed_product_validation)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(SUPPLYCHAIN_TRUST_GRAPH.GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC METRICS order_risk.revenue_at_risk DIMENSIONS order_risk.supplier_id WHERE order_risk.supplier_id = ''SUP-042'')'
    )
  );

-- Remove broad legacy access before granting the smaller zone-specific surface.
REVOKE SELECT ON ALL TABLES IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_READONLY;
REVOKE SELECT ON ALL VIEWS IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_READONLY;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_READONLY;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_READONLY;
REVOKE USAGE ON SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_READONLY;

REVOKE SELECT ON ALL TABLES IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE SELECT ON ALL VIEWS IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE INSERT, UPDATE ON TABLE CORE.MITIGATION_ACTIONS FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE INSERT ON TABLE CORE.AUDIT_EVENTS FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE INSERT, SELECT ON TABLE CORE.DECISION_IDEMPOTENCY FROM ROLE SUPPLYCHAIN_APP_RUNTIME;
REVOKE USAGE ON SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_RUNTIME;

GRANT USAGE ON SCHEMA GOVERNED TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNED TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNED TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT, REFERENCES ON FUTURE SEMANTIC VIEWS IN SCHEMA GOVERNED
  TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT USAGE ON SCHEMA WORKFLOW TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON TABLE WORKFLOW.MITIGATION_ACTIONS TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT USAGE ON SCHEMA AUDIT TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT ON TABLE AUDIT.AUDIT_EVENTS TO ROLE SUPPLYCHAIN_APP_READONLY;

GRANT USAGE ON SCHEMA GOVERNED TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNED TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNED TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT, REFERENCES ON FUTURE SEMANTIC VIEWS IN SCHEMA GOVERNED
  TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT USAGE ON SCHEMA WORKFLOW TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT, INSERT, UPDATE ON TABLE WORKFLOW.MITIGATION_ACTIONS
  TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT, INSERT ON TABLE WORKFLOW.DECISION_IDEMPOTENCY
  TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT USAGE ON SCHEMA AUDIT TO ROLE SUPPLYCHAIN_APP_RUNTIME;
GRANT SELECT, INSERT ON TABLE AUDIT.AUDIT_EVENTS TO ROLE SUPPLYCHAIN_APP_RUNTIME;

-- Deployment proof: no application role has a direct privilege in legacy CORE.
SELECT IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS LEGACY_CORE_ISOLATION
FROM SUPPLYCHAIN_TRUST_GRAPH.INFORMATION_SCHEMA.OBJECT_PRIVILEGES
WHERE OBJECT_SCHEMA = 'CORE'
  AND GRANTEE IN ('SUPPLYCHAIN_APP_READONLY', 'SUPPLYCHAIN_APP_RUNTIME');
