-- Remove residual grants that were materialized from the legacy future-view
-- grants before migration 005 revoked the future grant itself.

USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;

REVOKE SELECT ON ALL VIEWS IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_READONLY;
REVOKE SELECT ON ALL VIEWS IN SCHEMA CORE FROM ROLE SUPPLYCHAIN_APP_RUNTIME;

SELECT IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS LEGACY_CORE_OBJECT_ISOLATION
FROM SUPPLYCHAIN_TRUST_GRAPH.INFORMATION_SCHEMA.OBJECT_PRIVILEGES
WHERE OBJECT_SCHEMA = 'CORE'
  AND GRANTEE IN ('SUPPLYCHAIN_APP_READONLY', 'SUPPLYCHAIN_APP_RUNTIME');
