-- Forward-only upgrade: align the governed Snowflake metric with the runtime's
-- quantity-aware, cumulative allocation rule without replaying seed setup.

USE DATABASE SUPPLYCHAIN_TRUST_GRAPH;

UPDATE CORE.SHIPMENTS
SET QUANTITY = CASE SHIPMENT_ID
  WHEN 'SHP-8801' THEN 470
  WHEN 'SHP-8802' THEN 225
END
WHERE SHIPMENT_ID IN ('SHP-8801', 'SHP-8802')
  AND QUANTITY <> CASE SHIPMENT_ID
    WHEN 'SHP-8801' THEN 470
    WHEN 'SHP-8802' THEN 225
  END;

CREATE OR REPLACE VIEW CORE.GOVERNED_ORDER_RISK AS
WITH ACTIVE_DELAY AS (
  SELECT SUPPLIER_ID, DELAY_DAYS
  FROM CORE.DISRUPTION_EVENTS
  WHERE STATUS = 'ACTIVE'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SUPPLIER_ID ORDER BY REPORTED_AT DESC, DISRUPTION_ID DESC
  ) = 1
),
TARGET_INBOUND_RAW AS (
  SELECT
    D.SUPPLIER_ID,
    D.DELAY_DAYS,
    S.PART_ID,
    S.PLANT_ID,
    S.SHIPMENT_ID,
    S.QUANTITY AS TARGET_INBOUND_QUANTITY,
    S.PROMISED_DATE AS ORIGINAL_ETA,
    DATEADD('day', D.DELAY_DAYS, S.PROMISED_DATE) AS PROJECTED_ETA
  FROM ACTIVE_DELAY D
  JOIN CORE.SHIPMENTS S
    ON S.SUPPLIER_ID = D.SUPPLIER_ID AND S.STATUS = 'IN_TRANSIT'
),
TARGET_INBOUND AS (
  SELECT
    SUPPLIER_ID,
    DELAY_DAYS,
    PART_ID,
    PLANT_ID,
    LISTAGG(SHIPMENT_ID, ',') WITHIN GROUP (ORDER BY SHIPMENT_ID) AS SHIPMENT_IDS,
    SUM(TARGET_INBOUND_QUANTITY) AS INBOUND_QUANTITY,
    MIN(ORIGINAL_ETA) AS ORIGINAL_ETA,
    MIN(PROJECTED_ETA) AS PROJECTED_ETA
  FROM TARGET_INBOUND_RAW
  GROUP BY SUPPLIER_ID, DELAY_DAYS, PART_ID, PLANT_ID
),
LATEST_INVENTORY AS (
  SELECT *
  FROM CORE.INVENTORY
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PART_ID, PLANT_ID ORDER BY SNAPSHOT_AT DESC
  ) = 1
),
ORDER_CONTEXT AS (
  SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_TIER,
    O.PART_ID,
    P.PART_NAME,
    O.PLANT_ID,
    PL.PLANT_NAME,
    T.SUPPLIER_ID,
    T.SHIPMENT_IDS,
    T.DELAY_DAYS,
    O.REQUIRED_DATE,
    T.ORIGINAL_ETA,
    T.PROJECTED_ETA,
    O.ORDER_VALUE,
    O.QUANTITY AS ORDER_QUANTITY,
    GREATEST(L.ON_HAND - L.SAFETY_STOCK, 0) AS ALLOCATABLE_INVENTORY,
    T.INBOUND_QUANTITY,
    COALESCE(SUM(IFF(
      DATEADD(
        'day',
        IFF(S.SUPPLIER_ID = T.SUPPLIER_ID, T.DELAY_DAYS, 0),
        S.PROMISED_DATE
      ) <= O.REQUIRED_DATE,
      S.QUANTITY,
      0
    )), 0) AS INBOUND_BY_REQUIRED_DATE,
    O.SOURCE_SYSTEM AS ORDER_SOURCE_SYSTEM,
    L.SNAPSHOT_AT AS INVENTORY_SOURCE_TIMESTAMP
  FROM CORE.SALES_ORDERS O
  JOIN CORE.CUSTOMERS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
  JOIN CORE.PARTS P ON P.PART_ID = O.PART_ID
  JOIN CORE.PLANTS PL ON PL.PLANT_ID = O.PLANT_ID
  JOIN TARGET_INBOUND T ON T.PART_ID = O.PART_ID AND T.PLANT_ID = O.PLANT_ID
  JOIN LATEST_INVENTORY L ON L.PART_ID = O.PART_ID AND L.PLANT_ID = O.PLANT_ID
  LEFT JOIN CORE.SHIPMENTS S
    ON S.PART_ID = O.PART_ID
    AND S.PLANT_ID = O.PLANT_ID
    AND S.STATUS = 'IN_TRANSIT'
  WHERE O.STATUS = 'OPEN'
  GROUP BY ALL
),
ALLOCATED_ORDER_CONTEXT AS (
  SELECT
    *,
    SUM(ORDER_QUANTITY) OVER (
      PARTITION BY SUPPLIER_ID, PART_ID, PLANT_ID
      ORDER BY REQUIRED_DATE, ORDER_ID
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUMULATIVE_ORDER_DEMAND
  FROM ORDER_CONTEXT
)
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CUSTOMER_TIER,
  PART_ID,
  PART_NAME,
  PLANT_ID,
  PLANT_NAME,
  SUPPLIER_ID,
  SHIPMENT_IDS,
  REQUIRED_DATE,
  ORIGINAL_ETA,
  PROJECTED_ETA,
  ORDER_VALUE,
  ORDER_QUANTITY,
  ALLOCATABLE_INVENTORY,
  CUMULATIVE_ORDER_DEMAND,
  INBOUND_QUANTITY,
  INBOUND_BY_REQUIRED_DATE,
  ALLOCATABLE_INVENTORY + INBOUND_BY_REQUIRED_DATE
    < CUMULATIVE_ORDER_DEMAND AS IS_AT_RISK,
  IFF(
    ALLOCATABLE_INVENTORY + INBOUND_BY_REQUIRED_DATE
      < CUMULATIVE_ORDER_DEMAND,
    ORDER_VALUE,
    0
  ) AS AT_RISK_VALUE,
  ORDER_SOURCE_SYSTEM,
  INVENTORY_SOURCE_TIMESTAMP
FROM ALLOCATED_ORDER_CONTEXT;

CREATE OR REPLACE SECURE VIEW GOVERNED.ORDER_RISK COPY GRANTS AS
SELECT * FROM CORE.GOVERNED_ORDER_RISK;

CREATE OR REPLACE SEMANTIC VIEW GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TABLES (
    order_risk AS SUPPLYCHAIN_TRUST_GRAPH.GOVERNED.ORDER_RISK
      PRIMARY KEY (ORDER_ID)
      WITH SYNONYMS = ('affected orders', 'customer orders')
      COMMENT = 'Governed open-order impact grain'
  )
  FACTS (
    order_risk.order_value AS order_risk.ORDER_VALUE
      COMMENT = 'Committed open-order value in USD',
    order_risk.at_risk_value AS order_risk.AT_RISK_VALUE
      COMMENT = 'Order value included only when the quantity-aware at-risk test passes'
  )
  DIMENSIONS (
    order_risk.order_id AS order_risk.ORDER_ID,
    order_risk.customer_name AS order_risk.CUSTOMER_NAME,
    order_risk.customer_tier AS order_risk.CUSTOMER_TIER,
    order_risk.part_id AS order_risk.PART_ID,
    order_risk.part_name AS order_risk.PART_NAME,
    order_risk.plant_id AS order_risk.PLANT_ID,
    order_risk.plant_name AS order_risk.PLANT_NAME,
    order_risk.supplier_id AS order_risk.SUPPLIER_ID,
    order_risk.required_date AS order_risk.REQUIRED_DATE,
    order_risk.projected_eta AS order_risk.PROJECTED_ETA,
    order_risk.is_at_risk AS order_risk.IS_AT_RISK
      WITH SYNONYMS = ('late supply', 'order exposed')
  )
  METRICS (
    order_risk.revenue_at_risk AS SUM(order_risk.AT_RISK_VALUE)
      WITH SYNONYMS = ('exposed revenue', 'revenue exposure')
      COMMENT = 'Sum of open-order value where protected stock plus on-time inbound cannot satisfy cumulative demand',
    order_risk.orders_at_risk AS COUNT_IF(order_risk.IS_AT_RISK)
      COMMENT = 'Count of open orders passing the governed quantity-aware at-risk test'
  )
  COMMENT = 'Governed quantity-aware supply-chain impact model isolated in the analytics security zone'
  AI_SQL_GENERATION 'Use only declared metrics. Never substitute total order value for revenue_at_risk. Protect safety stock and allocate supply cumulatively.'
  AI_VERIFIED_QUERIES (
    sup_042_revenue_at_risk AS (
      QUESTION 'What revenue is at risk from the SUP-042 delay?'
      VERIFIED_AT 1790658000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(purpose = governed_product_validation)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(SUPPLYCHAIN_TRUST_GRAPH.GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC METRICS order_risk.revenue_at_risk DIMENSIONS order_risk.supplier_id WHERE order_risk.supplier_id = ''SUP-042'')'
    )
  );

GRANT SELECT, REFERENCES ON SEMANTIC VIEW GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TO ROLE SUPPLYCHAIN_APP_READONLY;
GRANT SELECT, REFERENCES ON SEMANTIC VIEW GOVERNED.SUPPLY_CHAIN_TRUST_GRAPH_SEMANTIC
  TO ROLE SUPPLYCHAIN_APP_RUNTIME;

SELECT IFF(
  SUM(AT_RISK_VALUE) = 586000 AND COUNT_IF(IS_AT_RISK) = 3,
  'PASS',
  'FAIL'
) AS QUANTITY_AWARE_BASELINE
FROM GOVERNED.ORDER_RISK
WHERE SUPPLIER_ID = 'SUP-042';
