[theme]
primaryColor = "#584BDC"
backgroundColor = "#F6F7FB"
secondaryBackgroundColor = "#FAFAFF"
textColor = "#22263A"
font = "sans-serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
